#!/usr/bin/ruby
=begin
  sshmenu-applet.rb 

  Copyright (c) 2005-2009, Grant McLean <grant@mclean.net.nz>

  This program is licenced under the terms of the License.txt file (a BSD-style
  license) distributed with the software.

require 'gnome-sshmenu'

require 'panelapplet2'

PanelApplet.main("OAFIID:GNOME_SSHMenuApplet_Factory",
                 "SSH Menu Applet", "0.1") do |applet, iid|
  if iid == "OAFIID:GNOME_SSHMenuApplet"
    app = GnomeSSHMenu::Factory.make_app(:window => applet, :args => [])
    applet.show
    true
  else
    false
  end
end
=end

require "rubygems"
require "ruby-libappindicator"

ai = AppIndicator::AppIndicator.new("test", "indicator-messages", AppIndicator::Category::APPLICATION_STATUS);

ai.set_menu(Gtk::Menu.new)
ai.set_status(AppIndicator::Status::ACTIVE)

Gtk.main